site_name: SmartScope
site_url: https://docs.smartscope.org
repo_url: https://github.com/NIEHS/SmartScope
repo_name: NIEHS/SmartScope

nav:
  - Home: 
    - Home: index.md
    - Participate: participate.md
  - Getting Started:
    - Requirements: getting_started/installation/requirements.md
    - Installation: 
      - Docker: getting_started/installation/docker/docker.md
      - Update: 
        - Update: getting_started/update/update_docker.md
        - Specific step for some updates: getting_started/update/to_0_9_1.md
    - Post-install setup:
      - External python setup: getting_started/post-install/external_python.md
      - Add your microscopes and detectors: getting_started/post-install/register_microscope.md
      - Low-dose presets: getting_started/post-install/low_dose.md
    - Administration: 
        - Admin Panel: getting_started/administration/admin_panel.md
        - Groups: getting_started/administration/groups.md
        - Users: getting_started/administration/users.md
        - Microscopes: getting_started/administration/microscopes.md
        - Detectors: getting_started/administration/detectors.md
  - Advanced Setup:
    - Environment variables: advanced_setup/environment.md
    - GPU passthrough: advanced_setup/gpu.md
    - Enabling HTTPS: advanced_setup/enable_https.md
    - Custom Data Paths: advanced_setup/custom_paths.md
    - External Plugins: advanced_setup/external_plugins.md
    - Edit default values: advanced_setup/edit_default_setup.md
    - Development:
      - Setting up a SmartScope Development Environment: advanced_setup/development/setup.md
      - Fake scope mode: advanced_setup/development/fake_scope.md
  - Use SmartScope:
    - Introduction: usage/introduction.md
    - User Interface:
      - Preparation:
        - Prepare SerialEM: usage/preparation/serialem.md
        - Session Setup: usage/preparation/setup_session.md
        - Preprocessing Pipeline: usage/preprocessing/preprocessing.md
        - Run a Session: usage/preparation/run_session.md
      - Browsing Results: 
        - Session Browser: usage/browsing/navigation.md
      - Report Panel:
        - Introduction: usage/report/introduction.md
        - Status Bar: usage/report/status_bar.md
        - Low-Magnification Maps: usage/report/low_mag_maps.md
        - High-Magnification Maps: usage/report/high_mag_maps.md
      - Data Collection:
        - Multishot per hole: usage/collection/multishot_per_hole.md
    - Detailed procedures:
      - Data collection: usage/detailed_procedures/data_collection.md
    - Acquisition procotols:
      - General information: usage/acquisition_protocols/general.md
      - SPA and SPA-precise: usage/acquisition_protocols/spa.md
      - NegativeStain: usage/acquisition_protocols/negative_stain.md
      - SPA-Ptolemy and SPA-Ptolemy-precise: usage/acquisition_protocols/spa_ptolemy.md
  - CLI:
    - Introduction: cli/introduction.md
    - Main commands: cli/main_commands.md
    - Maintenance commands: cli/maintenance_commands.md
    - Test commands: cli/test_commands.md
  - API:
    - REST API:
      - Programatic: api/rest/prog_api.md
      - Web Browser: api/rest/web_api.md
    - Plugin API:
      - Plugin Interface: api/plugin/interface.md
      - Configuration: api/plugin/configuration.md
      - Creating a Plugin: api/plugin/creating.md
    - Protocol API:
      - Configuration: api/protocol/configuration.md
      - Protocol Commands: api/protocol/protocol_commands.md
      - Automatic Protocol Selection: api/protocol/auto_protocol.md
  - Cite SmartScope: citation.md
  - Contact us: contact.md
theme:
  name: material
  logo: assets/icon256px.png
  favicon: assets/icon32px.png
  icon:
    repo: fontawesome/brands/git-alt
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - search.suggest
plugins:
  - search
  - table-reader
  - mkdocstrings:
      handlers:
        python:
          paths: ['./src/SmartScope/Smartscope', './src/external_plugins']

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
